<a href="https://colab.research.google.com/github/MadhawaAponso/Deeplearning_Tensorflow/blob/main/00_tensorFlowFundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#In this notebook we are going to do some fundementals in Tensorflow

# In this notebook we are going to do some fundementals in tensorflow
In this ,
1. Introduction
2.

#Introducton


#What is a Tensor?
A tensor is a multi-dimensional array used in TensorFlow for data representation. When you create a tensor using tf.constant, its values are fixed and cannot be changed.


In [2]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


#tf.constant
n TensorFlow, tf.constant is used to create a tensor whose value is fixed and cannot be changed. It is an immutable tensor, which makes it useful for storing constant values that are used repeatedly in computations but do not need to be updated.

In [3]:
# Create a scalar tensor : this have no dimention just a number
scalar = tf.constant(7)
print(scalar)  # Output: tf.Tensor(7, shape=(), dtype=int32)

# Create a vector tensor : This is one dimention tensor and
vector = tf.constant([1, 2, 3])
print(vector)  # Output: tf.Tensor([1 2 3], shape=(3,), dtype=int32)

# Create a matrix tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print(matrix)  # Output: tf.Tensor([[1 2 3] [4 5 6]], shape=(2, 3), dtype=int32)

# Create a 3-D tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor_3d)  # Output: tf.Tensor([[[1 2] [3 4]] [[5 6] [7 8]]], shape=(2, 2, 2), dtype=int32)

tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [4]:
#Dimension of each scaler , vector , matix and 3d tensor
print(scalar.ndim)
print(vector.ndim)
print(matrix.ndim)
print(tensor_3d.ndim)

0
1
2
3


In [5]:
#create with data type
matrix_1 = tf.constant([[1.,2.]
                        ,[3.,4.],
                        [5.,6.]],dtype=tf.float16)
print(matrix_1)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Totall  number of dimensions are how many elements in the shape()

In [7]:
tensor = tf.constant([[[1,2,3],[4,5,6]],
                     [[6,7,8],[8,9,10]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 8,  9, 10]]], dtype=int32)>



*   Scaler : a single numbe
*   vector : a number with direction
*   matrix : 2 dimensional array of numbers
*   tensor : n dimensional arrays of numbers





#tf.Varibale
In TensorFlow, a tf.Variable represents a tensor whose value can be changed during execution. It is typically used for storing weights and biases in neural networks or any other model parameters that need to be updated during training.

In [9]:
#using variable tensor
changeable_tensor = tf.Variable([1,2,3])
unchangeable_tensor = tf.constant([1,2,3])

print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [10]:
#now lets see wether we can change values in these tensors
changeable_tensor[0].assign(8) # [1,2,3]->[8,2,3]
#in changeable tensor it is posssible that we can change values

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([8, 2, 3], dtype=int32)>

In [ ]:
#but in unchangeable tensor it is not possible